image:
  tag: "2-alpine"

deployment:
  hostNetwork: true    # Caddy слушает порты 80/443 хоста

caddyfile:
  config: |
    # перенаправляем все на HTTPS
    http://${DOMAIN}/* {
      redir https://${DOMAIN}{uri}
    }

    ${N8N_HOST} {
      reverse_proxy n8n-stack-n8n.stack.svc.cluster.local:5678
      tls ${EMAIL}
    }

    ${SUPABASE_HOST} {
      reverse_proxy supabase-stack-supabase.stack.svc.cluster.local:54321
      tls ${EMAIL}
    }

    ${OPENWEBUI_HOST} {
      reverse_proxy openwebui-stack-openwebui.stack.svc.cluster.local:80
      tls ${EMAIL}
    }

    ${ZABBIX_HOST} {
      reverse_proxy zabbix-stack-zabbix.stack.svc.cluster.local:8080
      tls ${EMAIL}
    }
